import { Info, ShieldCheck } from 'lucide-react'
import { Card } from '../ui/Card'
import { ConfidenceBadge } from '../ui/ConfidenceBadge'
import { cn, formatConfidence } from '../../lib/utils'


/**
 * @param {{
 *   summary: string,
 *   confidence: number,
 *   matchedCount: number,
 *   missingCount: number,
 *   standardsCount: number,
 *   className?: string,
 * }} props
 */
export function GapSummaryCard({
  summary,
  confidence,
  matchedCount = 0,
  missingCount = 0,
  standardsCount = 0,
  className,
}) {
  const confidenceLabel =
    confidence >= 0.85 ? 'high' : confidence >= 0.6 ? 'medium' : 'low'

  return (
    <Card className={cn('p-5 sm:p-6 space-y-4 text-left shadow-[var(--shadow-card)]', className)}>
      {/* Header & Confidence */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border/60 pb-3">
        <div className="flex items-center gap-2">
          <ShieldCheck className="h-5 w-5 text-primary" aria-hidden="true" />
          <h2 className="text-base font-bold text-text">
            Executive Compliance Gap Analysis
          </h2>
        </div>

        <div className="flex items-center gap-2">
          <ConfidenceBadge label={confidenceLabel} value={confidence} />
          {typeof confidence === 'number' && (
            <span className="font-technical text-xs text-text-muted">
              Match Score: {formatConfidence(confidence)}
            </span>
          )}
        </div>
      </div>

      {/* Summary Narrative */}
      <div className="prose prose-sm max-w-none text-text">
        <p className="text-base leading-relaxed text-text font-medium">{summary}</p>
      </div>

      {/* Metric Breakdown Chips */}
      <div className="flex flex-wrap gap-2.5 pt-2 border-t border-border/60">
        <div className="flex items-center gap-1.5 rounded-[var(--radius-md)] border border-border bg-bg px-3 py-1.5 text-xs">
          <span className="text-text-muted">Applicable Standards:</span>
          <strong className="font-technical text-primary font-semibold">{standardsCount}</strong>
        </div>

        <div className="flex items-center gap-1.5 rounded-[var(--radius-md)] border border-green-200 bg-green-50/50 px-3 py-1.5 text-xs text-success">
          <span>Satisfied:</span>
          <strong className="font-technical font-bold">{matchedCount}</strong>
        </div>

        <div className="flex items-center gap-1.5 rounded-[var(--radius-md)] border border-amber-200 bg-amber-50/50 px-3 py-1.5 text-xs text-warning">
          <span>Missing / Needs Testing:</span>
          <strong className="font-technical font-bold">{missingCount}</strong>
        </div>
      </div>

      {/* Advisory Disclaimer */}
      <div className="flex items-start gap-2 rounded-[var(--radius-md)] bg-bg p-3 text-[11px] text-text-muted">
        <Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-text-muted" aria-hidden="true" />
        <span>
          This analysis is strictly generated by deterministic vector matching against indexed BIS standard clauses. It serves as engineering guidance and does not replace statutory third-party BIS laboratory certification.
        </span>
      </div>
    </Card>
  )
}
